import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const intern = Roboto({subsets: ["latin"], weight : "400"});  

export const metadata = {
  title: "Honeybee",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={intern.className}
      >
        <Header />
        {children}
        
        
      </body>
    </html>
  );
}
